"""
Tests for Node and RRTTree.
 
Assumes the classes under test (StateInfo, Node, RRTTree) live in a module
named `rrt` (i.e. `rrt.py` in the same directory). Change the import below
if your file is named differently.
 
Run with:
    pytest test_rrt.py -v

NOTE: all tests below generated by Claude
FIXME: changes have been made to rrt_util, so these tests are currently outdated
"""
 
import pytest
 
from xnew_rrt.rrt_util import StateInfo, Node, RRTTree
 

# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------
 
@pytest.fixture(autouse=True)
def reset_node_class_state():
    """
    Node.counter and Node.all_nodes are class-level (shared across every
    instance). Without resetting them between tests, tests would leak state
    into each other and node_id / all_nodes assertions would become order
    dependent. This fixture runs automatically before every test.
    """
    Node.counter = 0
    Node.all_nodes = []
    yield
    Node.counter = 0
    Node.all_nodes = []
 
 
def make_state(value):
    """Convenience factory for a minimal StateInfo with a single numeric
    'value' tucked into `state`, used as a stand-in for real robot state."""
    return StateInfo(
        state=value,
        dstate=0,
        bodies=None,
        moveable_obj_pose=None,
        moveable_obj_dstate=None,
    )
 
 
def euclidean_1d_distance(state_info_a, state_info_b):
    """Trivial distance function: absolute difference of `state` field."""
    return abs(state_info_a["state"] - state_info_b["state"])
 
 
def never_goal(state_info):
    return False
 
 
def goal_at(target_value):
    """Returns a goal_test function that succeeds when state == target_value."""
    def _goal_test(state_info):
        return state_info["state"] == target_value
    return _goal_test
 
 
# ---------------------------------------------------------------------------
# StateInfo tests
# ---------------------------------------------------------------------------
 
class TestStateInfo:
 
    def test_fields_stored(self):
        s = make_state(5)
        assert s.state == 5
        assert s.dstate == 0
 
    def test_getitem_matches_attributes(self):
        s = StateInfo(state=1, dstate=2, bodies=3,
                       moveable_obj_pose=4, moveable_obj_dstate=5)
        assert s["state"] == 1
        assert s["dstate"] == 2
        assert s["bodies"] == 3
        assert s["moveable_obj_pose"] == 4
        assert s["moveable_obj_dstate"] == 5
 
    def test_getitem_unknown_key(self):
        s = make_state(1)
        # Document current behavior: unknown key falls through to implicit
        # `None` (no explicit else/raise in __getitem__).
        assert s["not_a_real_key"] is None
 
 
# ---------------------------------------------------------------------------
# Node tests
# ---------------------------------------------------------------------------
 
class TestNode:
 
    def test_node_id_increments(self):
        n1 = Node(make_state(0), None)
        n2 = Node(make_state(1), None)
        n3 = Node(make_state(2), None)
        assert [n1.node_id, n2.node_id, n3.node_id] == [0, 1, 2]
 
    def test_all_nodes_tracks_every_instance(self):
        n1 = Node(make_state(0), None)
        n2 = Node(make_state(1), None)
        assert Node.all_nodes == [n1, n2]
 
    def test_all_nodes_reflects_later_mutation(self):
        """Objects in all_nodes are references, not copies -- mutating a
        node after creation should be visible through all_nodes."""
        parent = Node(make_state(0), None)
        child = Node(make_state(1), parent)
        parent.children.append(child)
 
        assert Node.all_nodes[0].children == [child]
        assert Node.all_nodes[0] is parent
 
    def test_children_defaults_to_empty_list(self):
        n = Node(make_state(0), None)
        assert n.children == []
 
    def test_parent_reference_stored(self):
        parent = Node(make_state(0), None)
        child = Node(make_state(1), parent)
        assert child.parent is parent
 
    def test_equality_based_on_node_id(self):
        n1 = Node(make_state(0), None)
        n2 = Node(make_state(0), None)
        # Same state contents, different node_id -> should NOT be equal.
        assert n1 != n2
 
    def test_equality_same_object(self):
        n1 = Node(make_state(0), None)
        assert n1 == n1
 
    def test_hashable_for_set_and_frozenset(self):
        """Node defines __eq__; per Python's data model this sets __hash__
        to None unless __hash__ is also explicitly defined. This test will
        fail until __hash__ is implemented on Node."""
        n1 = Node(make_state(0), None)
        n2 = Node(make_state(1), None)
        s = frozenset([n1, n2])
        assert n1 in s
        assert n2 in s
 
    def test_hash_consistent_with_equality(self):
        n1 = Node(make_state(0), None)
        assert hash(n1) == hash(n1)
 
 
# ---------------------------------------------------------------------------
# RRTTree tests
# ---------------------------------------------------------------------------
 
class TestRRTTreeConstruction:
 
    def test_root_is_node_instance(self):
        start = make_state(0)
        tree = RRTTree(start, euclidean_1d_distance, never_goal)
        assert isinstance(tree.root, Node)
 
    def test_root_state_matches_start(self):
        start = make_state(42)
        tree = RRTTree(start, euclidean_1d_distance, never_goal)
        assert tree.root.info["state"] == 42
 
    def test_root_has_no_parent(self):
        start = make_state(0)
        tree = RRTTree(start, euclidean_1d_distance, never_goal)
        assert tree.root.parent is None
 
    def test_root_registered_in_all_nodes(self):
        start = make_state(0)
        tree = RRTTree(start, euclidean_1d_distance, never_goal)
        assert tree.root in Node.all_nodes
 


class TestFindNearestTo:
 
    def test_finds_closest_of_multiple_nodes(self):
        tree = RRTTree(make_state(0), euclidean_1d_distance, never_goal)
        tree.add_edge(tree.root, make_state(10))
        tree.add_edge(tree.root, make_state(3))
        tree.add_edge(tree.root, make_state(-5))
 
        nearest = tree.find_nearest_to(make_state(4))
        assert nearest.info["state"] == 3
 
    def test_root_is_nearest_when_alone(self):
        tree = RRTTree(make_state(0), euclidean_1d_distance, never_goal)
        nearest = tree.find_nearest_to(make_state(100))
        assert nearest is tree.root

    def test_exact_match_returns_that_node(self):
        tree = RRTTree(make_state(0), euclidean_1d_distance, never_goal)
        tree.add_edge(tree.root, make_state(7))
        nearest = tree.find_nearest_to(make_state(7))
        assert nearest.info["state"] == 7


class TestAddEdge:
 
    def test_adds_child_to_parent(self):
        tree = RRTTree(make_state(0), euclidean_1d_distance, never_goal)
        tree.add_edge(tree.root, make_state(1))
        assert len(tree.root.children) == 1
        assert tree.root.children[0].info["state"] == 1
 
    def test_child_parent_pointer_set(self):
        tree = RRTTree(make_state(0), euclidean_1d_distance, never_goal)
        tree.add_edge(tree.root, make_state(1))
        child = tree.root.children[0]
        assert child.parent is tree.root
 
    def test_non_goal_state_returns_none(self):
        tree = RRTTree(make_state(0), euclidean_1d_distance, never_goal)
        result = tree.add_edge(tree.root, make_state(1))
        assert result is None
 
    def test_goal_state_returns_path(self):
        tree = RRTTree(make_state(0), euclidean_1d_distance, goal_at(5))
        mid = tree.add_edge(tree.root, make_state(3))
        # add_edge doesn't return the created node on non-goal, so grab it
        # from root.children to keep extending the branch
        mid_node = tree.root.children[0]
        path = tree.add_edge(mid_node, make_state(5))
 
        assert path is not None
        assert path[0] is tree.root
        assert path[-1].info["state"] == 5
 
    def test_goal_path_is_start_to_goal_order(self):
        tree = RRTTree(make_state(0), euclidean_1d_distance, goal_at(2))
        tree.add_edge(tree.root, make_state(1))
        n1 = tree.root.children[0]
        path = tree.add_edge(n1, make_state(2))
 
        values = [node.info["state"] for node in path]
        assert values == [0, 1, 2]
 
    def test_multiple_children_supported(self):
        tree = RRTTree(make_state(0), euclidean_1d_distance, never_goal)
        tree.add_edge(tree.root, make_state(1))
        tree.add_edge(tree.root, make_state(2))
        tree.add_edge(tree.root, make_state(3))
        assert len(tree.root.children) == 3
 
 
if __name__ == "__main__":
    import sys
    sys.exit(pytest.main([__file__, "-v"]))
 